name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: windows-2019
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Sed"
        run: |
          (Get-Content pyproject.toml).Replace('0.0.0.dev0', $Env:GITHUB_REF_NAME) | Set-Content pyproject.toml
          cat pyproject.toml
